name: Build project, run Lighthouse CI and uploads Lighthouse report on GithHub Pages

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd vite-project
          npm ci

      - name: run Lighthouse CI
        run: |
          cd vite-project
          npx lhci autorun || echo "LHCI failed!"

      - name: Upload report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./lighthouse-reports

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: lhci
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4